### ISSUE TITLE
CAGI5 dataset availability

### ISSUE THREAD

**Issue by d-laub** [amberT15/LLM_eval#1]
Hi there,

First of all, thank you for this work! I'm hoping to evaluate additional models but couldn't find the CAGI data referenced in the notebooks in the Zenodo archive. Could you point me to the right place or has it not been uploaded yet? Thanks again!

David

**Comment by amberT15** [comment]
Hi David,
Thanks for reaching out! Yes this work is still at pre-print and we are working on revisions. Thanks for letting me know that the datasets aren't fully provided through Zenodo. We'll definitely update it in the coming weeks. I can ping you here when we updated our repository.

**Comment by amberT15** [comment]
Hi David,
Following up on your question about the CAGI dataset. I have updated the Zenodo link in README. The CAGI dataset should be available in the new repository under data.tar.gz. Let me know if you have any questions!

**Comment by d-laub** [comment]
I can see it there now, thank you!
